packages/app/src/config/wagmi/config.default.ts
packages/app/src/config/wagmi/getWallets.ts

Closes FRO-641
Injects Safe wallet when using Spark app in safe iframe interface.

Add Safe wallet to wagmi config

---

packages/app/src/domain/hooks/useWalletType.ts

Fix actions not updating when using Spark through Safe app

---

packages/app/src/features/easy-borrow/logic/assets.ts
packages/app/src/features/easy-borrow/logic/useEasyBorrow.ts

Hide assets that cannot be used as collateral at easy borrow deposit selector

---

packages/app/src/domain/types/Token.test.ts
packages/app/src/domain/types/Token.ts
packages/app/src/domain/wallet/airdropInfo.ts
packages/app/src/features/navbar/Navbar.tsx
packages/app/src/features/navbar/components/NavbarActions.tsx
packages/app/src/features/navbar/components/airdrop-badge/AirdropBadge.stories.ts
packages/app/src/features/navbar/components/airdrop-badge/AirdropBadge.tsx
packages/app/src/features/navbar/components/airdrop-badge/AirdropDetails.tsx
packages/app/src/features/navbar/logic/useAirdropInfo.ts
packages/app/src/features/navbar/logic/useNavbar.ts
packages/app/src/features/navbar/types.ts
packages/app/src/features/navbar/utils/formatCompact.ts

Use real data at navbar airdrop hook

---

packages/app/.storybook/viewports.ts
packages/app/src/features/dashboard/components/create-position-panel/CreatePositionPanel.stories.tsx
packages/app/src/features/dashboard/components/skeleton/DasboardSkeleton.stories.ts
packages/app/src/features/dashboard/views/GuestView.stories.ts
packages/app/src/features/dialogs/borrow/views/BorrowView.stories.tsx
packages/app/src/features/dialogs/common/components/skeletons/DialogContentSkeleton.stories.tsx
packages/app/src/features/dialogs/deposit/views/DepositView.stories.tsx
packages/app/src/features/dialogs/repay/views/RepayView.stories.tsx
packages/app/src/features/dialogs/withdraw/views/WithdrawView.stories.tsx
packages/app/src/features/easy-borrow/components/skeleton/EasyBorrowSkeleton.stories.ts
packages/app/src/features/easy-borrow/views/SuccessView.stories.ts

Updates chromatic tablet viewport value to be not exactly at media breakpoint value.

Update chromatic tablet viewport value

---

packages/app/src/config/wagmi/config.e2e.ts
packages/app/src/domain/common/validation.ts
packages/app/src/domain/exchanges/lifi/validation.ts
packages/app/src/domain/wallet/airdropInfo.ts
packages/app/src/features/market-details/logic/useMarketDetails.ts
packages/app/src/features/market-details/logic/useMarketDetailsParams.ts

Cleanup zod validators

---

packages/app/.storybook/decorators.tsx
packages/app/src/features/actions/flavours/approve-delegation/useCreateApproveDelegationHandler.ts
packages/app/src/features/actions/flavours/approve/logic/useCreateApproveHandler.ts
packages/app/src/features/dialogs/savings/deposit/views/SavingsDepositView.stories.tsx
packages/app/src/features/dialogs/savings/withdraw/views/SavingsWithdrawView.stories.tsx

* makes errors in storybooks more obvious by improving query client config
* fix error propagation for approval actions
* Fix undeterministc stories 🥳 
Closes FRO-726

Correctly handle errors for approval actions + storybook fixes

---

packages/app/src/features/compliance/logic/useRestrictedAddressCheck.ts
packages/app/src/utils/sentry.ts

Also improves some http response status check

Ignore errors coming from @WalletConnect

---

packages/app/src/features/actions/ActionsContainer.PageObject.ts
packages/app/src/features/dialogs/borrow/BorrowDialog.test-e2e.ts
packages/app/src/features/dialogs/deposit/DepositDialog.test-e2e.ts
packages/app/src/features/dialogs/repay/RepayDialog.test-e2e.ts
packages/app/src/features/dialogs/savings/common/e2e/SavingsDialog.PageObject.ts
packages/app/src/features/dialogs/savings/deposit/SavingsDepositDialog.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/SavingsWithdrawDialog.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/WithdrawMaxDAI.test-e2e.ts
packages/app/src/features/dialogs/withdraw/WithdrawDialog.test-e2e.ts
packages/app/src/pages/Borrow.test-e2e.ts

Add e2e tests for native max DAI withdrawal

---

packages/app/src/domain/exchanges/lifi/query.ts

Closes FRO-761
Increases epsilon when asserting for slippage (now it's 1e-11).

Increase epsilon when asserting slippage

---

packages/app/src/domain/tokenized-vault-operations/useSexyDaiDeposit.test.ts
packages/app/src/domain/tokenized-vault-operations/useSexyDaiDeposit.ts
packages/app/src/domain/tokenized-vault-operations/useSexyDaiRedeemAll.test.ts
packages/app/src/domain/tokenized-vault-operations/useSexyDaiRedeemAll.ts
packages/app/src/domain/tokenized-vault-operations/useSexyDaiWithdraw.test.ts
packages/app/src/domain/tokenized-vault-operations/useSexyDaiWithdraw.ts
packages/app/src/domain/tokenized-vault-operations/useVaultRedeem.ts

Add hooks for gnosis sexy dai interactions

---

package.json
packages/app/src/features/easy-borrow/components/form/Deposits.tsx

Add easy borrow flow tooltip about some assets not being available

---

packages/app/src/domain/tokenized-vault-operations/useSexyDaiRedeem.test.ts
packages/app/src/domain/tokenized-vault-operations/useSexyDaiRedeem.ts
packages/app/src/features/actions/flavours/native-sdai-withdraw/xdai-from-sdai/types.ts
packages/app/src/features/actions/flavours/native-sdai-withdraw/xdai-from-sdai/useCreateXDaiFromSDaiWithdrawHandler.ts
packages/app/src/features/dialogs/savings/withdraw/logic/objectives.ts

Use redeem for gnosis xdai max withdrawal

---

packages/app/src/features/actions/ActionsContainer.PageObject.ts
packages/app/src/features/dialogs/savings/deposit/SavingsDepositDialog.test-e2e.ts
packages/app/src/features/dialogs/savings/deposit/e2e/mainnet/DepositDAI.test-e2e.ts
packages/app/src/features/dialogs/savings/deposit/e2e/mainnet/DepositUSDT.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/SavingsWithdrawDialog.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/mainnet/WithdrawDAI.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/mainnet/WithdrawUSDT.test-e2e.ts
packages/app/src/test/e2e/hars/200-usdt-from-sdai/53ce44d5e9e3be9aa346c6b8eedec813bd0d3f35.json
packages/app/src/test/e2e/hars/200-usdt-from-sdai/fe24e0700af0ec2a2a1e584e71e5e5547090556a.json
packages/app/src/test/e2e/hars/200-usdt-from-sdai/main.har
packages/app/src/test/e2e/hars/200-usdt-to-sdai/1dc9accecfdf8e56e91121f63cba0991d1ea8244.json
packages/app/src/test/e2e/hars/200-usdt-to-sdai/main.har

Savings validation e2e tests

---

packages/app/src/features/dashboard/components/borrow-table/components/EModeButton.tsx
packages/app/src/features/dialogs/borrow/BorrowDialog.test-e2e.ts
packages/app/src/features/dialogs/collateral/CollateralDialog.test-e2e.ts
packages/app/src/features/dialogs/collateral/views/SuccessView.tsx
packages/app/src/features/dialogs/common/Dialog.PageObject.ts
packages/app/src/features/dialogs/common/components/success-view/SuccessViewContent.tsx
packages/app/src/features/dialogs/e-mode/EModeDialog.PageObject.ts
packages/app/src/features/dialogs/e-mode/EModeDialog.test-e2e.ts
packages/app/src/features/dialogs/e-mode/views/SuccessView.tsx
packages/app/src/features/dialogs/savings/common/e2e/SavingsDialog.PageObject.ts
packages/app/src/features/dialogs/withdraw/WithdrawDialog.test-e2e.ts
packages/app/src/pages/Borrow.test-e2e.ts
packages/app/src/pages/Dashboard.PageObject.ts
packages/app/src/test/e2e/BasePageObject.ts
packages/app/src/ui/organisms/risk-acknowledgement/RiskAcknowledgement.tsx
packages/app/src/ui/utils/testIds.ts

Test liquidation risk warnings

---

packages/app/src/domain/psm-actions/redeem-and-swap/useRedeemAndSwap.test.ts
packages/app/src/domain/psm-actions/redeem-and-swap/useRedeemAndSwap.ts
packages/app/src/domain/psm-actions/useWithdrawAndSwap.test.ts
packages/app/src/domain/psm-actions/useWithdrawAndSwap.ts
packages/app/src/domain/tokenized-vault-operations/useSexyDaiRedeem.test.ts
packages/app/src/domain/tokenized-vault-operations/useSexyDaiRedeem.ts
packages/app/src/domain/tokenized-vault-operations/useSexyDaiWithdraw.test.ts
packages/app/src/domain/tokenized-vault-operations/useSexyDaiWithdraw.ts
packages/app/src/domain/tokenized-vault-operations/useVaultRedeem.test.ts
packages/app/src/domain/tokenized-vault-operations/useVaultRedeem.ts
packages/app/src/domain/tokenized-vault-operations/useVaultWithdraw.test.ts
packages/app/src/domain/tokenized-vault-operations/useVaultWithdraw.ts

Add optional receiver to withdraw/redeem savings hooks

---

packages/app/src/domain/hooks/useIsSmartContract.ts
packages/app/src/domain/hooks/useWalletType.ts
packages/app/src/domain/savings/validateReceiver.test.ts
packages/app/src/domain/savings/validateReceiver.ts
packages/app/src/features/dialogs/savings/withdraw/components/form/SavingsWithdrawDialogForm.tsx
packages/app/src/features/dialogs/savings/withdraw/logic/useSavingsWithdrawDialog.ts
packages/app/src/features/dialogs/savings/withdraw/logic/useSendModeExtension.ts
packages/app/src/features/dialogs/savings/withdraw/logic/validation.ts
packages/app/src/features/dialogs/savings/withdraw/types.ts

Add receiver form validation

---

.github/workflows/ci.yml
.github/workflows/ipfs-release.yml

Related issue: https://github.com/pnpm/action-setup/issues/135

Fix failing CI

---

packages/app/src/features/market-details/components/my-wallet/components/TokenBalance.tsx
packages/app/src/features/market-details/logic/makeWalletOverview.ts
packages/app/src/features/market-details/logic/useMarketDetails.ts
packages/app/src/pages/MarketDetails.PageObject.ts
packages/app/src/pages/MarketDetails.test-e2e.ts
packages/app/src/ui/utils/testIds.ts

feat: 🎸 sum market details wallet asset with its native equiv (#154)

---

packages/app/src/features/markets/components/debt-ceiling-progress/DebtCeilingProgress.stories.ts
packages/app/src/features/markets/components/debt-ceiling-progress/DebtCeilingProgress.tsx
packages/app/src/ui/atoms/progress/Progress.tsx

feat: 🎸 mark ceiling indicator red when limit is reached (#158)

---

packages/app/src/domain/analytics/index.ts
packages/app/src/domain/hooks/useIsSmartContract.ts
packages/app/src/domain/hooks/useWalletType.ts
packages/app/src/domain/hooks/useWrite.ts
packages/app/src/features/dialogs/sandbox/logic/createSandbox.ts

Basic analytics using plausible. 
Closes FRO-810

Basic analytics

---

packages/app/src/config/query-client.ts

Increase query client base retry delay

---

packages/app/src/domain/market-operations/useSetUseAsCollateral.ts
packages/app/src/domain/market-operations/useSetUserEMode.ts
packages/app/src/domain/migration-actions/useMigrateDAIToSNTS.test.ts
packages/app/src/domain/migration-actions/useMigrateSDAIAssetsToNST.test.ts
packages/app/src/domain/migration-actions/useMigrateSDAIAssetsToNST.ts
packages/app/src/domain/migration-actions/useMigrateSDAISharesToNST.test.ts
packages/app/src/domain/migration-actions/useMigrateSDAISharesToNST.ts
packages/app/src/domain/psm-actions/redeem-and-swap/useRedeemAndSwap.ts
packages/app/src/domain/psm-actions/useSwapAndDeposit.ts
packages/app/src/domain/psm-actions/useWithdrawAndSwap.ts
packages/app/src/domain/tokenized-vault-operations/useSexyDaiDeposit.ts
packages/app/src/domain/tokenized-vault-operations/useSexyDaiRedeem.ts
packages/app/src/domain/tokenized-vault-operations/useSexyDaiWithdraw.ts
packages/app/src/domain/tokenized-vault-operations/useVaultDeposit.ts
packages/app/src/domain/tokenized-vault-operations/useVaultRedeem.ts

Add migrate from sDai to NST (withdraw & redeem) hooks

---

packages/app/src/config/feature-flags/appConfig.default.ts
packages/app/src/features/actions/ActionsContainer.PageObject.ts
packages/app/src/features/dialogs/e-mode/EModeDialog.PageObject.ts
packages/app/src/features/dialogs/e-mode/EModeDialog.test-e2e.ts
packages/app/src/features/dialogs/e-mode/components/AvailableAssets.tsx
packages/app/src/features/dialogs/e-mode/components/LTVChange.tsx
packages/app/src/features/dialogs/e-mode/logic/getEModeCategories.ts
packages/app/src/pages/Dashboard.PageObject.ts
packages/app/src/ui/utils/testIds.ts

Add EMode dialog E2E tests

---

packages/app/src/features/dialogs/savings/common/components/transaction-overview/TransactionOverview.stories.ts
packages/app/src/features/dialogs/savings/common/components/transaction-overview/TransactionOverview.tsx
packages/app/src/features/dialogs/savings/common/e2e/SavingsDialog.PageObject.ts
packages/app/src/features/dialogs/savings/deposit/views/SavingsDepositView.tsx
packages/app/src/features/dialogs/savings/withdraw/e2e/gnosis/SendXDAI.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/gnosis/WithdrawMaxXDAI.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/gnosis/WithdrawXDAI.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/mainnet/SendDAI.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/mainnet/SendDAIValidation.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/mainnet/SendUSDC.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/mainnet/WithdrawDAI.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/mainnet/WithdrawMaxDAI.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/mainnet/WithdrawMaxUSDC.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/mainnet/WithdrawUSDC.test-e2e.ts

Remove APY row at send/withdraw savings tx overview

---

packages/app/src/domain/market-operations/useSupply.test.ts
packages/app/src/domain/market-operations/useSupply.ts
packages/app/src/features/actions/flavours/deposit/useCreateDepositHandler.ts

Use supply pool function instead of legacy deposit

---

packages/app/src/features/dialogs/common/logic/form.ts
packages/app/src/features/dialogs/savings/common/logic/form.ts
packages/app/src/utils/useDebounce.ts

Prevent risk acknowledgment from flashing at input changes

---

packages/app/src/features/actions/flavours/withdraw/logic/useCreateWithdrawHandler.ts
packages/app/src/features/actions/flavours/withdraw/logic/withdrawAction.test.ts
packages/app/src/features/actions/flavours/withdraw/logic/withdrawAction.ts
packages/app/src/features/actions/logic/useAction.ts
packages/app/src/features/actions/logic/useActionHandlers.ts
packages/app/src/features/dialogs/withdraw/WithdrawDialogContentContainer.tsx
packages/app/src/features/dialogs/withdraw/logic/useWithdrawDialog.ts
packages/app/src/features/dialogs/withdraw/views/WithdrawView.stories.tsx
packages/app/src/features/dialogs/withdraw/views/WithdrawView.tsx

Refactor withdraw actions

---

eslint.config.js
packages/app/src/domain/hooks/useWaitForTransactionReceiptGnosisSafe.test.ts
packages/app/src/domain/wallet/useTokens/useTokensInfo.test.ts
packages/app/src/features/dialogs/savings/deposit/logic/createTxOverview.ts
packages/app/src/test/e2e/forking/setupFork.ts

Add eslint rule for object shorthand

---

packages/app/src/features/dialogs/upgrade/UpgradeDialog.tsx
packages/app/src/features/dialogs/upgrade/UpgradeDialogContentContainer.tsx
packages/app/src/features/dialogs/upgrade/common/components/Banner.tsx
packages/app/src/features/dialogs/upgrade/common/components/Benefits.tsx
packages/app/src/features/dialogs/upgrade/common/components/Summary.tsx
packages/app/src/features/dialogs/upgrade/common/logic/createUpgradeObjectives.ts
packages/app/src/features/dialogs/upgrade/common/logic/useUpgradeDialog.ts
packages/app/src/features/dialogs/upgrade/dai-to-nst/views/UpgradeDaiToNSTView.stories.ts
packages/app/src/features/dialogs/upgrade/dai-to-nst/views/UpgradeDaiToNSTView.tsx
packages/app/src/features/savings-with-nst/components/cash-in-wallet/CashInWallet.stories.ts
packages/app/src/features/savings-with-nst/components/cash-in-wallet/CashInWallet.tsx
packages/app/src/features/savings-with-nst/components/cash-in-wallet/components/MoreDropdown.stories.ts
packages/app/src/features/savings-with-nst/components/cash-in-wallet/components/MoreDropdown.tsx
packages/app/src/features/savings-with-nst/components/cash-in-wallet/components/TokenCell.tsx
packages/app/src/features/savings-with-nst/components/cash-in-wallet/components/UpgradeTokenButton.tsx
packages/app/src/features/savings-with-nst/logic/useSavings.ts
packages/app/src/features/savings-with-nst/views/SavingsDaiAndNSTView.stories.ts
packages/app/src/features/savings-with-nst/views/SavingsDaiAndNSTView.tsx
packages/app/src/features/savings-with-nst/views/SavingsDaiView.tsx
packages/app/src/features/savings-with-nst/views/SavingsNSTView.tsx
packages/app/src/features/savings-with-nst/views/types.ts
packages/app/src/ui/assets/banners/upgrade-banner-bg.svg
packages/app/src/ui/assets/index.ts

Add upgrade dialog and handle dai to nst case

---

packages/app/src/features/actions/flavours/upgrade/logic/upgradeAction.test.ts
packages/app/src/features/actions/flavours/upgrade/logic/upgradeAction.ts
packages/app/src/features/dialogs/migrate/common/logic/useMigrateDialog.ts
packages/app/src/features/dialogs/migrate/upgrade/UpgradeDialogContentContainer.tsx
packages/app/src/features/dialogs/migrate/upgrade/views/UpgradeDaiToNSTView.tsx

Add sDAI to sNST migration config and test it

---

packages/app/src/domain/d3m-info/D3MInfoQuery.ts
packages/app/src/domain/d3m-info/types.ts
packages/app/src/features/market-details/components/market-overview/DaiMarketOverview.stories.ts
packages/app/src/features/market-details/components/market-overview/DaiMarketOverview.tsx
packages/app/src/features/market-details/components/market-overview/DefaultMarketOverview.tsx
packages/app/src/features/market-details/components/market-overview/MarketOverview.tsx
packages/app/src/features/market-details/components/market-overview/components/DetailsGrid.tsx
packages/app/src/features/market-details/components/market-overview/components/DetailsGridItem.tsx
packages/app/src/features/market-details/components/status-panel/BorrowStatusPanel.tsx
packages/app/src/features/market-details/components/status-panel/components/info-tile/InfoTile.tsx
packages/app/src/features/market-details/logic/makeDaiMarketOverview.ts
packages/app/src/features/market-details/types.ts
packages/app/src/locales/en.po

Extend D3M dss outline informations

---

packages/app/src/domain/hooks/useBlockExplorerAddressLink.ts
packages/app/src/domain/hooks/useBlockExplorerLink.ts
packages/app/src/domain/hooks/useGetBlockExplorerAddressLink.ts
packages/app/src/features/savings/components/cash-in-wallet/CashInWallet.stories.ts
packages/app/src/features/savings/components/cash-in-wallet/CashInWallet.tsx
packages/app/src/features/savings/components/cash-in-wallet/components/MoreDropdown.stories.ts
packages/app/src/features/savings/components/cash-in-wallet/components/MoreDropdown.tsx
packages/app/src/features/savings/logic/useSavings.ts
packages/app/src/features/savings/views/SavingsDaiAndUSDSView.stories.ts
packages/app/src/features/savings/views/SavingsDaiView.stories.ts
packages/app/src/features/savings/views/SavingsUSDSView.stories.ts
packages/app/src/features/savings/views/types.ts

Add learn more links to cash in wallet items

---

packages/app/src/features/savings/views/SavingsDaiAndUSDSView.tsx

Reintroduce welcome modal after regression

---

packages/app/src/features/actions/logic/useCreateActions.ts
packages/app/src/features/dialogs/common/components/alert/Alert.tsx
packages/app/src/features/easy-borrow/EasyBorrowContainer.tsx
packages/app/src/features/easy-borrow/components/BorrowRateBanner.tsx
packages/app/src/features/easy-borrow/components/EasyBorrowPanel.tsx
packages/app/src/features/easy-borrow/components/UsdsUpgradeAlert.tsx
packages/app/src/features/easy-borrow/components/form/Borrow.tsx
packages/app/src/features/easy-borrow/components/form/EasyBorrowForm.tsx
packages/app/src/features/easy-borrow/logic/assets.ts
packages/app/src/features/easy-borrow/logic/form/form.ts
packages/app/src/features/easy-borrow/logic/form/mapFormTokensToReserves.ts
packages/app/src/features/easy-borrow/logic/form/mapFormValuesToPositions.ts
packages/app/src/features/easy-borrow/logic/form/normalization.ts
packages/app/src/features/easy-borrow/logic/form/validation.ts
packages/app/src/features/easy-borrow/logic/types.ts
packages/app/src/features/easy-borrow/logic/useCreateObjectives.ts
packages/app/src/features/easy-borrow/logic/useEasyBorrow.ts
packages/app/src/features/easy-borrow/logic/useUpgradeOptions.ts
packages/app/src/features/easy-borrow/views/EasyBorrowView.stories.tsx
packages/app/src/features/easy-borrow/views/EasyBorrowView.tsx
packages/app/src/features/easy-borrow/views/SuccessView.stories.ts
packages/app/src/features/easy-borrow/views/SuccessView.tsx
packages/app/src/pages/Borrow.PageObject.ts
packages/app/src/pages/Borrow.test-e2e.ts
packages/app/src/ui/utils/testIds.ts

Closes FRO-946
USDS can be selected in form, but all calculation related to market data (updating user summary, liquidation price) are done based on dai reserve. I left some comments in code.

Enable USDS borrowing at easy borrow page

---

packages/app/src/config/abis/usdsPsmWrapperAbi.ts
packages/app/src/features/actions/ActionsContainer.PageObject.ts
packages/app/src/features/actions/components/actions-grid/ActionsGrid.tsx
packages/app/src/features/actions/components/actions-grid/stories/allActionHandlers.ts
packages/app/src/features/actions/flavours/stake/logic/createStakeActions.ts
packages/app/src/features/actions/flavours/usds-psm-wrap/UsdsPsmWrapActionRow.tsx
packages/app/src/features/actions/flavours/usds-psm-wrap/logic/usdsPsmWrapAction.test.ts
packages/app/src/features/actions/flavours/usds-psm-wrap/logic/usdsPsmWrapAction.ts
packages/app/src/features/actions/flavours/usds-psm-wrap/types.ts
packages/app/src/features/actions/logic/types.ts
packages/app/src/features/actions/logic/useContractAction.ts
packages/app/src/features/actions/logic/useCreateActions.ts
packages/app/src/features/dialogs/common/logic/title.ts

Add usds psm wrap action and use it in stake actions creation

---

packages/app/src/features/compliance/components/TermsOfService.tsx
packages/app/src/features/dialogs/claim-rewards/ClaimRewardsDialog.PageObject.ts
packages/app/src/features/dialogs/collateral/CollateralDialog.PageObject.ts
packages/app/src/features/dialogs/common/Dialog.PageObject.ts
packages/app/src/features/dialogs/common/components/success-view/SuccessViewCheckmark.tsx
packages/app/src/features/dialogs/e-mode/EModeDialog.PageObject.ts
packages/app/src/features/dialogs/savings/common/e2e/SavingsDialog.PageObject.ts
packages/app/src/features/dialogs/savings/migrate/downgrade/DowngradeDialog.PageObject.ts
packages/app/src/features/dialogs/savings/migrate/downgrade/views/DowngradeUSDSToDaiView.tsx
packages/app/src/features/dialogs/savings/migrate/upgrade/UpgradeDialog.PageObject.ts
packages/app/src/features/dialogs/savings/migrate/upgrade/views/UpgradeView.tsx
packages/app/src/features/easy-borrow/views/SuccessView.tsx
packages/app/src/features/market-details/components/market-overview/DaiMarketOverview.stories.ts
packages/app/src/features/market-details/components/market-overview/DaiMarketOverview.tsx
packages/app/src/features/market-details/components/market-overview/MarketOverview.tsx
packages/app/src/features/market-details/logic/makeDaiMarketOverview.ts
packages/app/src/features/market-details/types.ts
packages/app/src/features/savings/components/PageHeader.tsx
packages/app/src/features/savings/components/savings-opportunity/components/DSRLabel.tsx
packages/app/src/features/savings/components/savings-opportunity/components/Explainer.tsx
packages/app/src/features/savings/components/upgrade-savings-banner/UpgradeSavingsBanner.tsx
packages/app/src/features/savings/components/welcome-dialog/WelcomeDialog.tsx
packages/app/src/pages/Borrow.PageObject.ts
packages/app/src/pages/MarketDetails.test-e2e.ts
packages/app/src/ui/constants/links.ts

Finalize copy improvements

---

packages/app/src/features/actions/logic/stringifyObjectives.ts
packages/app/src/features/dialogs/savings/deposit/e2e/mainnet/DepositDAI.test-e2e.ts
packages/app/src/features/dialogs/savings/deposit/e2e/mainnet/DepositUSDC.test-e2e.ts

Refresh savings deposit action after switching savings token after approval

---

packages/app/.storybook/preview.ts
packages/app/src/domain/farms/farmsInfo.ts
packages/app/src/domain/hooks/useUnsupportedChain.ts
packages/app/src/features/farms/FarmsContainer.tsx
packages/app/src/features/farms/components/PageHeader.tsx
packages/app/src/features/farms/logic/useFarms.ts
packages/app/src/features/farms/views/FarmsView.tsx
packages/app/src/features/farms/views/UnsupportedChainView.stories.ts
packages/app/src/features/farms/views/UnsupportedChainView.tsx
packages/app/src/features/savings/SavingsContainer.tsx
packages/app/src/features/savings/logic/useSavings.ts
packages/app/src/ui/organisms/connect-or-sandbox-cta-panel/ConnectOrSandboxCTAPanel.tsx

Closes FRO-987
While working on this PR, we noticed regression with sandbox modal. Dialog shouldn't be closed when chain is changing. Related [ticket](https://linear.app/phoenixlabs/issue/FRO-994/make-dialog-close-on-chain-change-configurable)

Display unsupported chain view at farms

---

packages/app/.storybook/tokens.ts
packages/app/src/features/farm-details/dialogs/stake/components/transaction-overview/TransactionOutcome.tsx
packages/app/src/features/farm-details/dialogs/stake/components/transaction-overview/TransactionOverview.tsx
packages/app/src/features/farm-details/dialogs/stake/e2e/mainnet/StakeDAI.test-e2e.ts
packages/app/src/features/farm-details/dialogs/stake/e2e/mainnet/StakeSDAI.test-e2e.ts
packages/app/src/features/farm-details/dialogs/stake/e2e/mainnet/StakeSUSDS.test-e2e.ts
packages/app/src/features/farm-details/dialogs/stake/e2e/mainnet/StakeUSDC.test-e2e.ts
packages/app/src/features/farm-details/dialogs/stake/e2e/mainnet/StakeUSDS.test-e2e.ts
packages/app/src/features/farm-details/dialogs/unstake/UnstakeDialogContentContainer.tsx
packages/app/src/features/farm-details/dialogs/unstake/components/claim-rewards-switch/ExitFarmSwitch.stories.ts
packages/app/src/features/farm-details/dialogs/unstake/components/claim-rewards-switch/ExitFarmSwitch.tsx
packages/app/src/features/farm-details/dialogs/unstake/components/transaction-overview/TransactionOutcome.tsx
packages/app/src/features/farm-details/dialogs/unstake/components/transaction-overview/TransactionOverview.tsx
packages/app/src/features/farm-details/dialogs/unstake/logic/createTxOverview.ts
packages/app/src/features/farm-details/dialogs/unstake/logic/useUnstakeDialog.ts
packages/app/src/features/farm-details/dialogs/unstake/views/SuccessView.stories.ts
packages/app/src/features/farm-details/dialogs/unstake/views/SuccessView.tsx
packages/app/src/features/farm-details/dialogs/unstake/views/UnstakeView.stories.tsx
packages/app/src/features/farm-details/dialogs/unstake/views/UnstakeView.tsx
packages/app/src/ui/utils/testIds.ts

Add exit option in withdraw dialog

---

packages/app/src/features/actions/ActionsContainer.PageObject.ts
packages/app/src/features/farm-details/FarmDetails.PageObject.ts
packages/app/src/features/farm-details/components/active-farm-info-panel/ActiveFarmInfoPanel.tsx
packages/app/src/features/farm-details/components/farm-info-panel/FarmInfoPanel.tsx
packages/app/src/features/farm-details/dialogs/unstake/UnstakeDialog.PageObject.ts
packages/app/src/features/farm-details/dialogs/unstake/components/claim-rewards-switch/ExitFarmSwitch.tsx
packages/app/src/features/farm-details/dialogs/unstake/components/transaction-overview/TransactionOutcome.tsx
packages/app/src/features/farm-details/dialogs/unstake/e2e/mainnet/UnstakeUSDC.test-e2e.ts
packages/app/src/features/farm-details/dialogs/unstake/e2e/mainnet/UnstakeUSDS.test-e2e.ts
packages/app/src/features/farm-details/dialogs/unstake/e2e/mainnet/WithdrawMaxDai.test-e2e.ts
packages/app/src/features/farm-details/dialogs/unstake/e2e/mainnet/WithdrawMaxUSDC.test-e2e.ts
packages/app/src/features/farm-details/dialogs/unstake/e2e/mainnet/WithdrawMaxUSDS.test-e2e.ts
packages/app/src/features/farm-details/logic/useFarmDetails.ts
packages/app/src/features/farm-details/views/FarmDetailsView.stories.ts
packages/app/src/features/farm-details/views/FarmDetailsView.tsx
packages/app/src/ui/utils/testIds.ts

Add max withdraw and exit from farms tests

---

packages/app/src/features/farm-details/components/SRRTooltip.tsx
packages/app/src/features/farm-details/components/active-farm-info-panel/ActiveFarmInfoPanel.tsx
packages/app/src/features/farm-details/components/apr-over-time/AprOverTime.tsx
packages/app/src/features/farm-details/components/apr-over-time/components/Chart.tsx
packages/app/src/features/farm-details/components/farm-info-panel/FarmInfoPanel.tsx
packages/app/src/features/farm-details/components/farm-stats-row/FarmStatsRow.tsx
packages/app/src/ui/constants/links.ts

Improve copy after feedback

---

packages/app/playwright.config.ts

Set playwright retries back to original 3 to prevent test flakiness impacting whole test job.

Set e2e test retries back to 3

---

packages/app/src/features/farm-details/components/apr-over-time/RewardsOverTime.stories.ts
packages/app/src/features/farm-details/components/apr-over-time/RewardsOverTime.tsx
packages/app/src/features/farm-details/components/apr-over-time/components/ChartPanel.tsx
packages/app/src/features/farm-details/components/apr-over-time/components/RewardsChartPanel.tsx
packages/app/src/ui/atoms/delayed-component/DelayedComponent.tsx

Refactor rewards chart panel to accept loading and error states

---

packages/app/src/features/actions/flavours/deposit-to-savings/logic/createDepositToSavingsActions.ts
packages/app/src/features/actions/flavours/deposit-to-savings/logic/depositToSavingsAction.ts
packages/app/src/features/actions/flavours/deposit-to-savings/logic/getSavingsDepositActionPath.ts
packages/app/src/features/actions/flavours/withdraw-from-savings/logic/createWithdrawFromSavingsActions.ts
packages/app/src/features/actions/flavours/withdraw-from-savings/logic/getSavingsWithdrawActionPath.ts
packages/app/src/features/actions/flavours/withdraw-from-savings/logic/withdrawFromSavingsAction.ts
packages/app/src/features/actions/utils/savings.ts

Refactor savings logic to use explicitly defined paths

---

packages/app/src/features/actions/flavours/stake/logic/createStakeActions.ts
packages/app/src/features/actions/flavours/stake/logic/getStakeActionPath.ts
packages/app/src/features/actions/flavours/unstake/logic/createUnstakeActions.ts
packages/app/src/features/actions/flavours/unstake/logic/getUnstakeActionPath.ts

Refactor stake and unstake actions creation to use action path switch

---

packages/app/package.json
packages/app/src/config/chain/index.ts
packages/app/src/config/contracts-generated.ts
packages/app/src/domain/savings-info/baseSavingsInfo.ts
packages/app/wagmi.config.ts
pnpm-lock.yaml

Add base savings info

---

packages/app/src/config/chain/index.ts
packages/app/src/features/savings/logic/useSavings.ts

Make savings page to render on base

---

packages/app/.storybook/tokens.ts
packages/app/src/config/chain/constants.ts
packages/app/src/config/chain/index.ts
packages/app/src/config/chain/types.ts
packages/app/src/domain/farms/getFarmBlockchainDetails.ts
packages/app/src/features/actions/flavours/claim-farm-rewards/logic/claimFarmRewardsAction.test.ts
packages/app/src/features/actions/flavours/stake/logic/stakeAction.test.ts
packages/app/src/features/actions/flavours/unstake/logic/unstakeAction.test.ts
packages/app/src/features/farm-details/FarmDetails.PageObject.ts
packages/app/src/features/farm-details/components/apy-tooltip/ApyTooltip.tsx
packages/app/src/features/farm-details/components/chronicle-points-tooltip/ChroniclePointsTooltip.tsx
packages/app/src/features/farm-details/components/farm-info-panel/active/ActiveFarmInfoPanel.stories.ts
packages/app/src/features/farm-details/components/farm-info-panel/active/ActiveFarmInfoPanel.tsx
packages/app/src/features/farm-details/components/farm-info-panel/active/RewardPointsSyncWarning.tsx
packages/app/src/features/farm-details/components/farm-info-panel/inactive/InactiveFarmInfoPanel.stories.ts
packages/app/src/features/farm-details/components/farm-info-panel/inactive/InactiveFarmInfoPanel.tsx
packages/app/src/features/farm-details/dialogs/stake/views/StakeView.stories.tsx
packages/app/src/features/farm-details/dialogs/unstake/views/UnstakeView.stories.tsx
packages/app/src/features/farm-details/views/FarmDetailsView.stories.ts
packages/app/src/features/farm-details/views/FarmDetailsView.tsx
packages/app/src/features/farms/components/farm-tile/FarmTile.tsx
packages/app/src/features/farms/views/FarmsView.stories.ts
packages/app/src/features/savings/logic/useSavings.ts
packages/app/src/pages/Farms.test-e2e.ts

Farms panels updates

---

packages/app/src/ui/layouts/app-layout/components/PageNotSupportedWarning.tsx

I've put `96px` equiv. height - prev. height was equal to `78px`. Also `96px` is a target height from figma

Increase NotSupportedWarning height according to design

---

packages/app/src/features/dialogs/convert-stables/e2e/base/UsdcToUsds.test-e2e.ts
packages/app/src/features/dialogs/convert-stables/e2e/base/UsdsToUsdc.test-e2e.ts

Add base convert stables dialog tests

---

packages/app/src/features/actions/settings-dialog/constants.ts
packages/app/src/features/savings/components/stablecoins-in-wallet/StablecoinsInWallet.tsx

Improve text at convert stables panel

---

packages/app/src/ui/atoms/new/close-button/CloseButton.stories.tsx
packages/app/src/ui/atoms/new/close-button/CloseButton.tsx
packages/app/src/ui/atoms/new/icon-box/IconBox.tsx
packages/app/src/ui/molecules/new/alert/Alert.stories.tsx
packages/app/src/ui/molecules/new/alert/Alert.tsx
packages/app/tailwind.config.ts

Add new alert component

---

packages/app/.storybook/preview.ts
packages/app/src/ui/atoms/new/select/Select.stories.tsx
packages/app/src/ui/atoms/new/tooltip/Tooltip.stories.tsx
packages/app/src/ui/atoms/new/tooltip/Tooltip.tsx
packages/app/src/ui/molecules/new/asset-selector/AssetSelector.stories.tsx
packages/app/src/ui/molecules/new/topbar-navigation/TopbarNavigation.stories.tsx

radix ui doesnt support rounded arrows

Add Tooltip

---

packages/app/src/ui/atoms/new/switch/Switch.tsx
packages/app/tailwind.config.ts

Update switch styles

---

packages/app/src/domain/common/risk.ts
packages/app/src/features/dialogs/savings/withdraw/components/form/AddressInput.tsx
packages/app/src/ui/atoms/new/badge/Badge.stories.tsx
packages/app/src/ui/atoms/new/badge/Badge.tsx
packages/app/src/ui/atoms/new/icon-box/IconBox.tsx
packages/app/src/ui/molecules/asset-input/AssetInput.tsx
packages/app/src/ui/molecules/new/alert/Alert.tsx
packages/app/src/ui/molecules/new/topbar-navigation/TopbarButton.tsx
packages/app/src/ui/organisms/new/asset-input/AssetInput.tsx
packages/app/src/ui/organisms/transaction-overview/rows/TransactionOverviewAmountChange.tsx
packages/app/src/ui/organisms/transaction-overview/rows/TransactionOverviewApyChange.tsx
packages/app/src/ui/organisms/transaction-overview/rows/TransactionOverviewAvailableAssets.tsx
packages/app/src/ui/organisms/transaction-overview/rows/TransactionOverviewHealthFactorChange.tsx
packages/app/src/ui/organisms/transaction-overview/rows/TransactionOverviewMaxLtvChange.tsx
packages/app/src/ui/organisms/transaction-overview/rows/TransactionOverviewRoute.tsx
packages/app/tailwind.config.ts

Add badge component

---

packages/app/src/ui/atoms/new/panel/Panel.stories.tsx
packages/app/src/ui/atoms/new/panel/Panel.tsx

Add base panel component

---

packages/app/src/features/savings/components/upgrade-savings-banner/UpgradeSavingsBanner.tsx
packages/app/src/features/savings/views/SavingsDaiAndUSDSView.stories.ts
packages/app/src/ui/assets/banners/savings-upgrade.svg
packages/app/src/ui/assets/index.ts
packages/app/tailwind.config.ts

Restyle upgrade savings dai banner

---

packages/app/src/features/actions/settings-dialog/components/SettingsDialogContent.tsx
packages/app/src/features/dialogs/savings/deposit/components/BenefitsDialog.tsx
packages/app/src/features/dialogs/savings/deposit/components/UpgradeToSusdsSwitch.tsx
packages/app/src/features/farm-details/dialogs/unstake/components/claim-rewards-switch/ExitFarmSwitch.tsx
packages/app/src/ui/molecules/data-table/components/SwitchCell.tsx
packages/app/src/ui/molecules/labeled-switch/LabeledSwitch.tsx

Update dialog switch panels

---

packages/app/src/ui/assets/page/farms-icon.svg

Farms new icon

---

packages/app/src/features/markets/components/summary-tile/SummaryTile.tsx
packages/app/src/features/markets/components/summary-tile/components/Tile.stories.tsx
packages/app/src/features/markets/components/summary-tile/components/Tile.tsx
packages/app/src/features/markets/components/summary-tiles/SummaryTiles.tsx

Change markets summary icons

---

packages/app/src/features/savings/components/stablecoins-in-wallet/StablecoinsInWallet.tsx
packages/app/src/ui/atoms/dialog/Dialog.tsx

Fix mobile dialog height

---

packages/app/src/config/chain/index.ts

Update base api endpoints for savings

---

packages/app/src/features/my-portfolio/components/my-wallet-panel/MyWalletChart.tsx
packages/app/src/ui/atoms/new/health-factor-gauge/HealthFactorGauge.tsx

Fixes issue with rendering health factor indicator in Safari

Replace conic gradient in hf indicator with linear gradient

---

packages/app/src/ui/constants/links.ts

Remove html extension from terms of use and privacy links

---

packages/app/src/features/actions/flavours/stake/logic/stakeAction.test.ts
packages/app/src/features/actions/flavours/stake/logic/stakeAction.ts

Add referral code to farm stake action

---

package.json
packages/app/src/features/easy-borrow/components/UsdsUpgradeAlert.tsx
packages/app/src/features/easy-borrow/views/SuccessView.tsx
packages/app/src/ui/layouts/app-layout/AppLayout.tsx

Improve look of easy borrow success view

---

packages/app/src/features/farm-details/components/back-nav/BackNav.tsx
packages/app/src/features/farms/components/PageHeader.tsx
packages/app/src/features/market-details/views/components/BackNav.tsx
packages/app/src/features/market-details/views/components/CompactView.tsx
packages/app/src/features/market-details/views/components/FullView.tsx
packages/app/src/features/markets/MarketsContainer.tsx
packages/app/src/features/markets/logic/useMarkets.ts
packages/app/src/features/markets/views/MarketsView.stories.ts
packages/app/src/features/markets/views/MarketsView.tsx
packages/app/src/ui/atoms/new/network-badge/NetworkBadge.stories.tsx
packages/app/src/ui/atoms/new/network-badge/NetworkBadge.tsx

Add network badge component

---

packages/app/src/features/market-details/components/charts/interest-yield/components/Chart.tsx

Change colors and add gradient at utilization rate chart

---

packages/app/src/config/chain/constants.ts

Place Base as a second chain in network selector

---

packages/app/src/config/wagmi/getWallets.ts

Add OKX wallet

---

packages/app/src/domain/hooks/useWrite.ts
packages/app/src/features/actions/logic/types.ts
packages/app/src/features/actions/logic/useBatchActionHandler.ts
packages/app/src/features/actions/logic/useBatchHandler.ts
packages/app/src/features/actions/logic/useBatchWrite.ts
packages/app/src/features/actions/logic/useContractAction.ts

Add hook for getting batch action handler

---

packages/app/src/config/query-client.ts
packages/app/src/config/wagmi/config.default.ts
packages/app/src/config/wagmi/getWallets.ts
packages/app/src/features/actions/ActionsContainer.tsx
packages/app/src/features/actions/logic/useActionHandlers.ts
packages/app/src/features/actions/logic/useActions.ts
packages/app/src/features/actions/logic/useActionsContext.ts
packages/app/src/features/actions/logic/useBatchStatus.ts
packages/app/src/features/actions/logic/useCanWalletBatch.ts
packages/app/src/features/actions/logic/useCreateActions.ts
packages/app/src/features/dialogs/savings/migrate/upgrade/views/UpgradeView.stories.tsx
packages/app/src/features/easy-borrow/views/EasyBorrowView.stories.tsx
packages/app/src/features/topbar/logic/usePrefetchCanWalletBatchQuery.ts
packages/app/src/features/topbar/logic/useTopbar.ts
packages/app/src/test/integration/constants.ts
packages/app/src/utils/promiseWithTimeout.ts

Actions master hook

---

packages/app/src/features/savings/components/accounts-navigation/AccountsNavigation.stories.tsx
packages/app/src/features/savings/components/accounts-navigation/AccountsNavigation.tsx

Implement savings accounts navigation component

---

packages/common-universal/src/types/NormalizedUnitNumber.test.ts
packages/common-universal/src/types/NormalizedUnitNumber.ts

Add support for more arguments in min function

---

packages/app/src/ui/molecules/copy-button/CopyButton.tsx
packages/app/src/utils/useClipboard.ts

Add fallback clipboard mechanism that will work in iframe environment

---

packages/app/src/features/savings/SavingsContainer.tsx
packages/app/src/features/savings/components/account-main-panel-group/AccountMainPanelGroup.tsx
packages/app/src/features/savings/components/deposit-cta-panel/DepositCTAPanel.stories.ts
packages/app/src/features/savings/components/deposit-cta-panel/DepositCTAPanel.tsx
packages/app/src/features/savings/components/general-stats-bar/GeneralStatsBar.tsx
packages/app/src/features/savings/components/savings-account/SavingsAccount.tsx
packages/app/src/features/savings/logic/useSavings.ts
packages/app/src/features/savings/views/SavingsView.stories.ts
packages/app/src/features/savings/views/SavingsView.tsx

Display general stats bar

---

packages/app/src/features/market-details/components/charts/interest-yield/InterestYieldChart.tsx
packages/app/src/features/savings/components/savings-account/SavingsAccount.tsx
packages/app/src/ui/charts/components/ChartTabsPanel.tsx
packages/app/src/ui/utils/useElementSize.ts

Fix chart width in savings view layout

---

packages/app/src/domain/common/validation.ts
packages/app/src/features/savings/SavingsContainer.tsx
packages/app/src/features/savings/components/general-stats-bar/GeneralStatsBar.stories.ts
packages/app/src/features/savings/components/general-stats-bar/GeneralStatsBar.tsx
packages/app/src/features/savings/components/skeleton/SavingsSkeleton.tsx
packages/app/src/features/savings/logic/general-stats/generalStatsQueryOptions.ts
packages/app/src/features/savings/logic/general-stats/useGeneralStats.ts
packages/app/src/features/savings/logic/general-stats/usePrefetchSavingsGeneralStats.ts
packages/app/src/features/savings/logic/useSavings.ts
packages/app/src/features/savings/views/SavingsView.stories.ts
packages/app/src/features/savings/views/SavingsView.tsx
packages/app/src/features/topbar/logic/useTopbar.ts

Fill general stats bar with api data

---

packages/app/src/features/savings/components/account-main-panel-group/AccountMainPanelGroup.stories.ts
packages/app/src/features/savings/components/account-main-panel-group/AccountMainPanelGroup.tsx
packages/app/src/features/savings/components/account-main-panel-group/BottomPanel.tsx
packages/app/src/features/savings/components/account-main-panel-group/SidePanelGroup.tsx
packages/app/src/features/savings/components/deposit-cta-panel/components/Header.tsx
packages/app/src/features/savings/components/savings-account/SavingsAccount.tsx
packages/app/src/features/savings/logic/getInterestData.ts
packages/app/src/features/savings/logic/projections.ts
packages/app/src/features/savings/logic/useSavings.ts
packages/app/src/features/savings/types.ts
packages/app/src/features/savings/views/SavingsView.stories.ts
packages/app/src/pages/Savings.PageObject.ts
packages/app/src/pages/Savings.test-e2e.ts
packages/app/src/ui/utils/testIds.ts

Display apy data when user has funds deposited

---

packages/app/src/features/savings/SavingsContainer.tsx
packages/app/src/features/savings/components/deposit-cta-panel/DepositCTAPanel.stories.ts
packages/app/src/features/savings/components/deposit-cta-panel/DepositCTAPanel.tsx
packages/app/src/features/savings/components/deposit-cta-panel/components/Actions.tsx
packages/app/src/features/savings/components/savings-account/SavingsAccount.tsx
packages/app/src/features/savings/logic/useSavings.ts
packages/app/src/features/savings/views/SavingsView.stories.ts
packages/app/src/features/savings/views/SavingsView.tsx

Disable sandbox button when in sandbox

---

packages/app/src/features/actions/logic/useCanWalletBatch.ts
packages/app/src/features/topbar/logic/usePrefetchCanWalletBatchQuery.ts

Improve suspense handling in withdraw dialog actions

---

packages/app/src/config/contracts-generated.ts
packages/app/src/domain/hooks/useIncreasedGasLimit.ts
packages/app/src/features/actions/flavours/convert-stables/logic/createConvertStablesActions.ts
packages/app/src/features/actions/flavours/deposit-to-savings/logic/createDepositToSavingsActions.ts
packages/app/src/features/actions/flavours/deposit-to-savings/logic/depositToSavingsAction.ts
packages/app/src/features/actions/flavours/deposit-to-savings/logic/depositToSavingsActionBase.test.ts
packages/app/src/features/actions/flavours/psm-convert/logic/psmConvertAction.ts
packages/app/src/features/actions/flavours/psm-convert/logic/psmConvertActionBase.test.ts
packages/app/src/features/actions/flavours/withdraw-from-savings/logic/createWithdrawFromSavingsActions.ts
packages/app/src/features/actions/flavours/withdraw-from-savings/logic/withdrawFromSavingsAction.ts
packages/app/src/features/actions/flavours/withdraw-from-savings/logic/withdrawFromSavingsActionBase.test.ts
packages/app/src/features/dialogs/savings/deposit/e2e/base/usds-account/DepositUSDC.test-e2e.ts
packages/app/src/features/dialogs/savings/deposit/e2e/base/usds-account/DepositUSDS.test-e2e.ts
packages/app/src/features/dialogs/savings/deposit/logic/useDepositToSavingsValidator.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/base/usdc-account/WithdrawUSDC.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/base/usds-account/WithdrawMaxUSDS.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/base/usds-account/WithdrawUSDC.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/base/usds-account/WithdrawUSDS.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/logic/useWithdrawFromSavingsValidator.ts
packages/app/wagmi.config.ts

Update wagmi config with arbitrum contracts

---

packages/app/src/config/wagmi/config.e2e.ts
packages/app/src/features/dialogs/savings/deposit/e2e/arbitrum/usds-account/DepositUSDC.test-e2e.ts
packages/app/src/features/dialogs/savings/deposit/e2e/arbitrum/usds-account/DepositUSDS.test-e2e.ts
packages/app/src/test/e2e/constants.ts
packages/app/src/test/e2e/setup.ts

Add arbitrum savings deposit tests

---

packages/app/src/features/dialogs/savings/withdraw/e2e/arbitrum/usds-account/SendUSDC.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/arbitrum/usds-account/SendUSDS.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/arbitrum/usds-account/WithdrawMaxUSDC.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/arbitrum/usds-account/WithdrawMaxUSDS.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/arbitrum/usds-account/WithdrawUSDC.test-e2e.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/arbitrum/usds-account/WithdrawUSDS.test-e2e.ts

Add arbitrum savings withdraw e2e tests

---

packages/app/src/features/savings/components/dai-legacy-account-banner/DaiLegacyAccountBanner.stories.ts
packages/app/src/features/savings/components/dai-legacy-account-banner/DaiLegacyAccountBanner.tsx
packages/app/src/features/savings/components/savings-account/SavingsAccount.tsx
packages/app/src/features/savings/views/SavingsView.stories.ts

Display dai legacy account banner

---

packages/app/src/features/dialogs/select-network/views/SelectNetworkDialogView.tsx

Align network available features text to left

---

packages/app/src/features/savings/components/dai-legacy-account-banner/DaiLegacyAccountBanner.tsx
packages/app/src/features/savings/components/entry-assets-panel/EntryAssetsPanel.tsx
packages/app/src/features/savings/components/savings-account/SavingsAccount.tsx
packages/app/src/pages/Savings.PageObject.ts
packages/app/src/pages/Savings.test-e2e.ts
packages/app/src/ui/utils/testIds.ts

Disable convert dialog in guest mode

---

packages/app/src/features/savings/components/deposit-cta-panel/DepositCTAPanel.tsx
packages/app/src/features/savings/components/deposit-cta-panel/components/Actions.tsx

Do not show sandbox button when in sandbox

---

packages/app/src/features/savings/SavingsContainer.tsx
packages/app/src/features/savings/components/general-stats-bar/GeneralStatsBar.stories.ts
packages/app/src/features/savings/components/general-stats-bar/GeneralStatsBar.tsx
packages/app/src/features/savings/logic/useSavings.ts
packages/app/src/features/savings/types.ts
packages/app/src/features/savings/utils/getAccountMetadata.ts
packages/app/src/features/savings/views/SavingsView.stories.ts
packages/app/src/features/savings/views/SavingsView.tsx
packages/app/src/ui/constants/links.ts

Add tooltip next to savings liquidity number

---

packages/app/.storybook/preview.ts
packages/app/.storybook/viewports.ts
packages/app/src/features/my-portfolio/components/borrow-table/BorrowTable.stories.tsx

Update viewports to match commonely used devices

---

packages/app/src/config/chain/configs/base.ts
packages/app/src/features/dialogs/savings/withdraw/e2e/base/usdc-account/WithdrawUSDC.test-e2e.ts

Put usds account first on base

---

packages/app/src/features/savings/components/general-stats-bar/GeneralStatsBar.stories.ts
packages/app/src/features/savings/components/general-stats-bar/GeneralStatsBar.tsx
packages/app/src/features/savings/logic/general-stats/generalStatsQueryOptions.ts
packages/app/src/features/savings/views/SavingsView.stories.ts

Show savings liquidity stat only for usdc

---

packages/app/src/domain/spark-rewards/ongoingCampaignsQueryOptions.ts
packages/app/src/features/rewards/components/ongoing-campaigns-panel/OngoingCampaignsPanel.stories.ts
packages/app/src/features/rewards/components/ongoing-campaigns-panel/OngoingCampaignsPanel.tsx
packages/app/src/features/rewards/logic/useOngoingCampaigns.ts
packages/app/src/features/rewards/types.ts

Add hook to fetch ongoing campaigns

---

packages/app/src/features/spark-rewards/components/active-rewards-panel/ActiveRewardsPanel.tsx
packages/app/src/features/spark-rewards/components/claim-all-panel/ClaimAllPanel.tsx
packages/app/src/features/spark-rewards/views/RewardsView.tsx

Improve error and loading views for spark rewards

---

packages/app/src/features/farms/components/farm-tile/FarmTile.tsx
packages/app/src/features/savings/components/deposit-cta-panel/components/Details.tsx
packages/app/src/features/spark-rewards/SparkRewardsContainer.tsx
packages/app/src/features/spark-rewards/components/active-rewards-panel/ActiveRewardsPanel.stories.ts
packages/app/src/features/spark-rewards/components/active-rewards-panel/ActiveRewardsPanel.tsx
packages/app/src/features/spark-rewards/components/claim-all-panel/ClaimAllPanel.tsx
packages/app/src/features/spark-rewards/components/earn-rewards-banner/EarnRewardsBanner.stories.ts
packages/app/src/features/spark-rewards/components/earn-rewards-banner/EarnRewardsBanner.tsx
packages/app/src/features/spark-rewards/components/ongoing-campaigns-panel/OngoingCampaignsPanel.stories.ts
packages/app/src/features/spark-rewards/components/ongoing-campaigns-panel/OngoingCampaignsPanel.tsx
packages/app/src/features/spark-rewards/views/AccountConnectingView.stories.ts
packages/app/src/features/spark-rewards/views/AccountConnectingView.tsx
packages/app/src/features/spark-rewards/views/GuestView.tsx
packages/app/src/features/spark-rewards/views/RewardsView.stories.ts
packages/app/src/ui/assets/index.ts
packages/app/src/ui/assets/page/borrow-icon-circle.svg
packages/app/src/ui/assets/page/farms-icon-circle.svg
packages/app/src/ui/assets/page/savings-icon-circle.svg
packages/app/src/ui/molecules/icon-stack/IconStack.stories.tsx
packages/app/src/ui/molecules/icon-stack/IconStack.tsx

Handle rewards page empty states

---

packages/app/src/config/paths.ts
packages/app/src/features/dialogs/select-network/logic/useSelectNetworkDialog.ts

Fix dangling comma at network selector

---

packages/app/src/features/spark-rewards/components/active-rewards-panel/ActiveRewardsPanel.stories.ts
packages/app/src/features/spark-rewards/components/claim-all-panel/ClaimAllPanel.stories.ts
packages/app/src/features/spark-rewards/components/claim-all-panel/ClaimAllPanel.tsx
packages/app/src/features/spark-rewards/views/RewardsView.stories.ts

Take care of zero amount rewards

---

packages/app/.storybook/tokens.ts
packages/app/src/domain/e-mode/constants.ts
packages/app/src/features/dialogs/e-mode/components/CategoriesGrid.tsx
packages/app/src/features/dialogs/e-mode/components/EModeCategoryTile.tsx
packages/app/src/features/dialogs/e-mode/logic/getEModeCategories.ts
packages/app/src/features/dialogs/e-mode/views/EModeView.stories.ts
packages/app/src/features/market-details/logic/makeMarketOverview.ts

Add btc e mode

---

packages/app/src/features/savings/components/deposit-cta-panel/DepositCTAPanel.tsx
packages/app/src/features/savings/components/deposit-cta-panel/components/Details.tsx
packages/app/src/features/savings/components/deposit-cta-panel/components/Header.tsx

Fix deposit cta component layout

---

packages/app/src/features/dialogs/claim-rewards/ClaimRewardsDialog.PageObject.ts
packages/app/src/features/dialogs/claim-rewards/views/SuccessView.tsx
packages/app/src/features/dialogs/claim-spark-rewards/ClaimSparkRewardsContainer.tsx
packages/app/src/features/dialogs/claim-spark-rewards/logic/useClaimSparkRewardsDialog.ts
packages/app/src/features/dialogs/claim-spark-rewards/views/ClaimSparkRewards.stories.ts
packages/app/src/features/dialogs/claim-spark-rewards/views/ClaimSparkRewardsView.tsx
packages/app/src/features/dialogs/claim-spark-rewards/views/SuccessView.stories.ts
packages/app/src/features/dialogs/claim-spark-rewards/views/SuccessView.tsx
packages/app/src/features/dialogs/common/Dialog.PageObject.ts
packages/app/src/features/dialogs/common/components/success-view/SuccessViewContent.tsx
packages/app/src/features/dialogs/common/components/success-view/SuccessViewTokenRow.tsx
packages/app/src/features/dialogs/e-mode/EModeDialog.PageObject.ts
packages/app/src/features/dialogs/savings/migrate/upgrade/UpgradeDialog.PageObject.ts
packages/app/src/features/spark-rewards/components/claim-all-panel/ClaimAllPanel.tsx
packages/app/src/features/spark-rewards/logic/useClaimableRewardsSummary.ts
packages/app/src/test/e2e/assertions.ts
packages/app/src/ui/utils/testIds.ts

Add logic to claim all rewards button

---

packages/app/src/features/top-banner/UsdcSavingsTopBanner.tsx
packages/app/src/features/top-banner/UsdcSavingsTopBannet.stories.ts
packages/app/src/ui/layouts/app-layout/AppLayout.tsx

Add usdc savings top banner

---

packages/app/src/features/savings/components/deposit-cta-panel/DepositCTAPanel.stories.ts
packages/app/src/features/savings/utils/getAccountMetadata.ts
packages/app/src/features/savings/views/SavingsView.stories.ts
packages/app/src/ui/constants/links.ts

Update docs links for savings usdc

---

packages/app/src/features/actions/flavours/deposit-to-savings/logic/depositToSavingsAction.test.ts
packages/app/src/features/actions/flavours/deposit-to-savings/logic/depositToSavingsAction.ts
packages/app/src/features/actions/flavours/deposit-to-savings/logic/depositToSavingsActionBase.test.ts
packages/app/src/features/actions/flavours/deposit-to-savings/logic/depositToSexyDaiAction.test.ts
packages/app/src/features/actions/logic/types.ts
packages/app/src/features/actions/logic/useContractAction.ts
packages/app/src/features/dialogs/savings/deposit/logic/useSavingsDepositDialog.ts
packages/app/src/features/dialogs/savings/withdraw/views/SavingsWithdrawView.stories.tsx
packages/app/src/features/farm-details/dialogs/unstake/views/UnstakeView.stories.tsx

Track savings deposits as separate events

---

packages/app/src/utils/sentry/shouldErrorBeTracked.ts

Add new filters to sentry

---

packages/app/src/features/analytics/components/CookieBanner.tsx
packages/app/src/features/dialogs/select-network/views/SelectNetworkDialogView.tsx
packages/app/src/features/easy-borrow/components/form/LoanToValueSlider.tsx
packages/app/src/features/market-details/components/debt-ceiling-progress/Progress.tsx
packages/app/src/features/market-details/components/spark-airdrop-info-panel/SparkAirdropInfoPanel.tsx
packages/app/src/features/my-portfolio/components/position/Position.tsx
packages/app/src/features/spark-staking/components/stake-cta-panel/StakeSparkCTAPanel.stories.ts
packages/app/src/features/spark-staking/components/stake-cta-panel/StakeSparkCTAPanel.tsx
packages/app/src/ui/assets/spark-staking/stake-cta-panel-bg.svg
packages/app/src/ui/atoms/button/Button.tsx
packages/app/src/ui/constants/links.ts
packages/app/tailwind.config.ts

Add stake spark call to action panel

---

packages/app/src/features/farm-details/components/farm-info-panel/active/ActiveFarmInfoPanel.tsx
packages/app/src/features/spark-staking/components/staking-rewards-panel/StakingRewardsPanel.stories.ts
packages/app/src/features/spark-staking/components/staking-rewards-panel/StakingRewardsPanel.tsx
packages/app/src/ui/assets/spark-staking/staking-rewards-panel-bg.svg
packages/app/src/ui/molecules/growing-reward/GrowingReward.tsx

Add staking rewards panel

---

packages/app/src/features/actions/flavours/deposit-to-savings/logic/depositToSavingsAction.ts
packages/app/src/features/errors/NotConnected.tsx
packages/app/src/utils/sentry/shouldErrorBeTracked.ts

Do not require wallet type to be defined when sending tracking event

---

packages/app/src/config/contracts-generated.ts
packages/app/src/domain/spark-rewards/claimableRewardsQueryOptions.ts
packages/app/src/domain/spark-rewards/setSparkRewards.ts
packages/app/src/features/actions/components/actions/stories/allActionHandlers.ts
packages/app/src/features/actions/flavours/claim-spark-rewards/logic/claimSparkRewardsAction.test.ts
packages/app/src/features/actions/flavours/claim-spark-rewards/logic/claimSparkRewardsAction.ts
packages/app/src/features/actions/flavours/claim-spark-rewards/types.ts
packages/app/src/features/actions/logic/useCreateActions.ts
packages/app/src/features/dialogs/claim-spark-rewards/logic/useClaimSparkRewardsDialog.ts
packages/app/src/features/dialogs/claim-spark-rewards/views/ClaimSparkRewards.stories.ts
packages/app/src/features/dialogs/sandbox/logic/setupSparkRewards.ts
packages/app/src/features/spark-rewards/logic/useClaimableRewards.test.ts
packages/app/wagmi.config.ts

Handle both spark staking and campaigns rewards by claim action

---

packages/app/src/features/dialogs/e-mode/EModeDialog.test-e2e.ts
packages/app/src/test/e2e/constants.ts

Add BTC e-mode category e2e tests

---

packages/app/src/css/main.css
packages/app/src/features/topbar/components/topbar-navigation/TopbarButton.tsx
packages/app/src/features/topbar/components/topbar-navigation/TopbarNavigation.stories.tsx
packages/app/src/features/topbar/components/topbar-navigation/TopbarNavigation.tsx
packages/app/src/features/topbar/components/topbar-navigation/TopbarNavigationDialog.tsx
packages/app/src/features/topbar/components/topbar-navigation/components/SparkTokenNavLinkContent.tsx
packages/app/src/features/topbar/components/topbar-navigation/constants.tsx
packages/app/src/features/topbar/components/topbar/Topbar.stories.tsx
packages/app/src/features/topbar/logic/useNavigationInfo.ts
packages/app/tailwind.config.ts

Add SPK page navigation item

---

packages/app/src/features/markets/components/airdrop-badge/AirdropBadge.tsx
packages/app/src/features/topbar/components/topbar-airdrop/TopbarAirdropDropdown.tsx
packages/app/src/features/topbar/components/topbar-menu/components/TopbarMenuAirdropItem.tsx
packages/app/src/ui/constants/text.ts

Update pre-farming airdrop eligibility text

---

packages/common-universal/src/httpClient/HttpClient.ts

Decided to simply return response so in cases where we need to do something unconventional we can do custom stuff with the HTTP response
Closes: TS-345

Add raw methods to HttpClient

---

packages/app/src/features/spk-staking/components/staking-rewards-panel/StakingRewardsPanel.stories.ts
packages/app/src/features/spk-staking/components/staking-rewards-panel/StakingRewardsPanel.tsx
packages/app/src/features/spk-staking/logic/useSpkStaking.ts
packages/app/src/features/spk-staking/views/SpkStakingView.stories.ts
packages/app/src/ui/molecules/growing-reward/GrowingReward.tsx
packages/app/src/utils/useTimestamp.ts
packages/app/tailwind.config.ts

Handle out of sync spk stake reward

---

packages/app/src/features/spk-staking/components/staking-rewards-panel/StakingRewardsPanel.tsx
packages/app/src/ui/assets/index.ts
packages/app/src/ui/assets/spark-staking/in-sync-status-icon.svg
packages/app/src/ui/assets/spark-staking/syncing-status-icon.svg
packages/app/tailwind.config.ts

Add rewards amount status detail

---

packages/app/src/features/actions/flavours/finalize-spk-unstake/logic/finalizeSpkUnstakeAction.test.ts
packages/app/src/features/actions/flavours/stake-spk/logic/stakeSpkAction.test.ts
packages/app/src/features/actions/flavours/unstake-spk/logic/unstakeSpkAction.test.ts
packages/app/src/features/spk-staking/components/stake-cta-panel/StakeSpkCTAPanel.stories.ts
packages/app/src/features/spk-staking/components/stake-cta-panel/StakeSpkCTAPanel.tsx
packages/app/src/features/spk-staking/components/staking-rewards-panel/StakingRewardsPanel.tsx
packages/app/src/features/spk-staking/dialogs/stake/logic/useStakeDialog.ts
packages/app/src/features/spk-staking/logic/useSpkStaking.ts
packages/app/src/features/spk-staking/logic/useSpkStakingData.ts
packages/app/src/features/spk-staking/views/SpkStakingView.stories.ts
packages/app/src/ui/organisms/transaction-overview/rows/TransactionOverviewApyChange.tsx
packages/app/src/ui/organisms/transaction-overview/rows/TransactionOverviewFarmApy.tsx
packages/app/src/ui/organisms/transaction-overview/rows/TransactionOverviewSavingsApy.tsx

Polish SPK staking
