sparkdotfi/spark-app

packages/app/src/features/market-details/components/charts/market-overview/MarketOverviewChart.tsx
Turns out that on Safari `svg` element in a flex container is shrinked to minimal possible size, which was `0 0` in our case.
=> Fix utilisation charts on Safari

packages/app/src/features/market-details/components/spark-info-panel/SparkInfoPanel.stories.tsx, packages/app/src/features/market-details/components/spark-info-panel/SparkInfoPanel.tsx, packages/app/src/features/market-details/components/status-panel/BorrowStatusPanel.tsx, packages/app/src/features/market-details/components/status-panel/EModeStatusPanel.tsx, packages/app/src/features/market-details/components/status-panel/SupplyStatusPanel.tsx, packages/app/src/features/market-details/logic/makeDaiMarketOverview.ts, packages/app/src/features/market-details/logic/makeMarketOverview.ts, packages/app/src/features/market-details/logic/useMarketDetails.ts, packages/app/src/features/market-details/types.ts, packages/app/src/features/market-details/views/MarketDetailsView.stories.ts, packages/app/src/features/market-details/views/components/CompactView.tsx, packages/app/src/features/market-details/views/components/FullView.tsx, packages/app/src/ui/atoms/docs-link/DocsLink.tsx, packages/app/src/utils/getDisplyTokenSymbol.ts
- Airdrop information added to market details pages
- New molecule component added for creating Spark informations
- Extracted docs link to atom component
=> Add Spark airdrop info to market details

packages/app/src/config/chain/index.ts, packages/app/src/config/chain/types.ts, packages/app/src/domain/exchanges/lifi/meta/useLifiQueryMetaEvaluator.ts
- Removed flag `supportsLifiWaivedFees` from chain config.
- Made `useLifiQueryMetaEvaluator` hook return waived fee integrator for specified routes on Gnosis chain.
=> Enable waiving LiFi fees on Gnosis chain

packages/app/src/config/wagmi/config.default.ts, packages/app/src/domain/hooks/useWaitForTransactionReceiptGnosisSafe.test.ts, packages/app/src/domain/hooks/useWaitForTransactionReceiptGnosisSafe.ts, packages/app/src/domain/hooks/useWaitForTransactionReceiptUniversal.ts, packages/app/src/test/integration/expect.ts, packages/app/src/test/integration/mockTransport/handlers.ts, packages/app/src/test/integration/wagmi-config.ts
- Replaces `webSocket` transport with `http` transport in default wagmi config.
- Refactors `useWaitForTransactionReceiptGnosisSafe` to actively query for logs on every new block, instead of using subscription mechanisms.
- Adds `getLogsCall` handler for integration tests.
- Adds `createBlockNumberCallHandler` and `createGetLogsHandler` which effectively allows to simulate blockchain state change in integration tests.
=> Use getLogs method instead of watching events in useWaitForGnosisTransaction

packages/app/src/features/dialogs/borrow/BorrowDialog.test-e2e.ts
The previous waiting mechanism was flawed as we waited for DAI to appear in deposit table. This also included DAI appearing in wallet balances. Because wallet balances and market info are separate queries, we didn't actually wait for new market info to be fetched correctly, which could lead to situations where borrow dialog validation was stuck with outdated market info.
=> Fix waiting for setup execution in borrow dialog E2E tests

packages/app/src/utils/sentry.ts
All errors in sentry were trimmed to default `maxValueLength` parameter in Sentry - 250. This makes it impossible to fully read contract function execution errors, as they are oftentimes longer than 250 characters. This PR increases the `maxValueLength` to 5000.
=> Increase sentry max value length

packages/app/.env.production, packages/app/.env.staging, packages/app/.storybook/decorators.tsx, packages/app/.storybook/preview.ts, packages/app/src/config/consts.ts, packages/app/src/config/paths.ts, packages/app/src/domain/farms/getFarm.ts, packages/app/src/domain/farms/query.ts, packages/app/src/domain/farms/useFarmsInfo.ts, packages/app/src/domain/wallet/useTokens/createAssetDataFetcher.ts, packages/app/src/domain/wallet/useTokens/createOraclePriceFetcher.ts, packages/app/src/domain/wallet/useTokens/query.ts, packages/app/src/domain/wallet/useTokens/useTokensInfo.ts, packages/app/src/features/farm-details/FarmDetailsContainer.tsx, packages/app/src/features/farm-details/components/active-farm-info-panel/EarnedBalance.tsx, packages/app/src/features/farm-details/logic/historic/query.ts, packages/app/src/features/farm-details/logic/historic/types.ts, packages/app/src/features/farm-details/logic/historic/useFarmHistoricData.ts, packages/app/src/features/farm-details/logic/useFarmDetails.ts, packages/app/src/features/farm-details/logic/useFarmDetailsParams.ts, packages/app/src/features/farms/logic/getFarmTileData.ts, packages/app/vite.config.ts
- Adds `useFarmHistoricData` hook
- Adds simple version of `useFarmDetails` hook
- Fixes timestamp in stories
=> Add historical data fetching for APR chart

package.json, packages/app/package.json, packages/app/playwright.config.ts, packages/app/src/features/dialogs/savings/deposit/e2e/mainnet/DepositUSDC.test-e2e.ts, patches/playwright@1.47.2.patch, pnpm-lock.yaml
It looks like fix is not yet available on latest release. I looked at [PR](https://github.com/microsoft/playwright/issues/26350), and it has label `1.48` attached, while the current release is `1.47.2`. I suspect it might take some time until available.
EDIT: I've patched playwright to include given fix.
=> Tweak playwright configuration to fail after few failures

packages/app/playwright.config.ts
Closes FRO-1008
`maxFailures` flag works best when tests are running with only one worker.
In case when we have multiple failing tests in tests suits from same directory, playwright will distribute those tests among 16 workers. Each of this tests can hit timeout (3 minutes, e.g., when locator is wrongly written). So in final, we had:
- one failed test: 3 minutes
- 3 retries each of them 3 minutes
- in total 12 minutes for one test to be marked as failed
If `maxFailures` is set to more than `1`, first worker available will take and run another test, which will add to the pile.
This PR is reproduction of yesterday's failing PR, in which 20 min timeout was hit, but with slightly modified playwright config to check if tests will give result faster:
- maxFailures = 1
- timeout = 2 minutes
- …
=> Adjust playwright test config to get test report faster

packages/app/.storybook/tokens.ts, packages/app/src/features/savings/components/growing-balance/GrowingBalance.tsx, packages/app/src/features/savings/components/savings-token-panel/SavingsTokenPanel.stories.ts, packages/app/src/features/savings/components/savings-token-panel/SavingsTokenPanel.tsx, packages/app/src/features/savings/logic/makeSavingsOverview.ts, packages/app/src/features/savings/logic/makeSavingsTokenDetails.ts, packages/app/src/features/savings/logic/useSavings.ts, packages/app/src/features/savings/views/GuestView.stories.ts, packages/app/src/features/savings/views/GuestView.tsx, packages/app/src/features/savings/views/SavingsDaiAndUSDSView.stories.ts, packages/app/src/features/savings/views/SavingsDaiAndUSDSView.tsx, packages/app/src/features/savings/views/SavingsDaiView.stories.ts, packages/app/src/features/savings/views/SavingsDaiView.tsx, packages/app/src/features/savings/views/SavingsUSDSView.stories.ts, packages/app/src/features/savings/views/SavingsUSDSView.tsx
Closes FRO-1033
Note: I've updated storybook dai price to be exactly `1` (so it matches our app reality). There is a lot of changes in stories because of that, but they are only cosmetic ones, where usd formatted value was displayed.
=> Refactor savings counter rendering

packages/app/src/features/savings/components/navbar-item/SavingsAPYBadge.tsx, packages/app/src/ui/atoms/dropdown/DropdownMenu.tsx, packages/app/src/ui/atoms/new/button/Button.tsx, packages/app/src/ui/atoms/new/close-button/CloseButton.tsx, packages/app/src/ui/atoms/new/icon-box/IconBox.tsx, packages/app/src/ui/atoms/new/select/Select.tsx, packages/app/src/ui/atoms/new/switch/Switch.tsx, packages/app/src/ui/atoms/new/tooltip/Tooltip.tsx, packages/app/src/ui/molecules/new/alert/Alert.tsx, packages/app/src/ui/molecules/new/asset-selector/AssetSelector.tsx, packages/app/src/ui/molecules/new/topbar-navigation/TopbarButton.tsx, packages/app/src/ui/molecules/new/topbar-navigation/TopbarNavigation.tsx, packages/app/src/ui/organisms/new/asset-input/AssetInput.tsx, packages/app/tailwind.config.ts
Moved `bg` and `border` from `colors` to it's own properties (`borderColor` and `backgroundColor`) in tailwind config. It simplified classes usage, e.g.:
`bg-reskin-bg-primary-inverse` -> `bg-primary-inverse`
`border-reskin-border-primary` -> `border-primary`.
In addition, not having `bg/border` directly in colors config prevents from using those in unrelated context - for example you can't do `ring-reskin-border-primary`, which makes sense, since ring is a shadow and normally shouldn't have access to border color properties (default behavior in tailwind).
=> Refactor tailwind config colors

packages/app/src/ui/atoms/new/button/Button.stories.tsx, packages/app/src/ui/atoms/new/button/Button.tsx, packages/app/src/ui/atoms/new/icon-button/IconButton.stories.tsx, packages/app/src/ui/atoms/new/icon-button/IconButton.tsx
Quick poc to show how we can have flexibility of providing custom icons to Button, but at the same time having Icon scaled correctly depending on button size, without explicitly passing same size prop for button and icon each time.
Using button with icon could look like:
```<Button size="m"><ButtonIcon icon={PlusIcon} />Button Text</Button>```
You pass variant only for `Button`, and `ButtonIcon` is automatically getting it thanks that it's wrapped by `Button` component.
I saw similar pattern before in radix and shadcn.
https://github.com/shadcn-ui/ui/blob/500a353816969e3cce2b3f4f0699ce4e6ad06f0b/apps/www/registry/default/ui/carousel.tsx#L24
=> Remove postfix and prefix icons from button props

packages/app/src/ui/atoms/link/Link.tsx, packages/app/src/ui/atoms/new/tooltip/Tooltip.tsx, packages/app/tailwind.config.ts
=> Update link component

README.md
Vercel, during build, will automatically use latest pnpm version.
To make Vercel use specific pnpm version:
- environment variable at Vercel's project must be added: `ENABLE_EXPERIMENTAL_COREPACK=1`
- specific pnpm version must be set at root package.json: `"packageManager": "pnpm@9.14.2"`
=> Add readme note about enforcing pnpm version at Vercel's build

packages/app/src/features/easy-borrow/EasyBorrowContainer.tsx, packages/app/src/features/easy-borrow/components/EasyBorrowPanel.tsx, packages/app/src/features/easy-borrow/logic/useEasyBorrow.ts, packages/app/src/features/easy-borrow/views/EasyBorrowView.stories.tsx, packages/app/src/features/easy-borrow/views/EasyBorrowView.tsx
=> Scroll to actions after hitting borrow button

packages/app/src/features/dialogs/borrow/logic/form.ts, packages/app/src/features/dialogs/common/logic/transfer-from-user/form.ts, packages/app/src/features/dialogs/deposit/logic/form.ts, packages/app/src/features/dialogs/savings/deposit/e2e/General.test-e2e.ts, packages/app/src/features/dialogs/savings/withdraw/e2e/mainnet/General.test-e2e.ts, packages/app/src/features/dialogs/savings/withdraw/logic/getFormFieldsForWithdrawDialog.ts, packages/app/src/features/dialogs/withdraw/logic/form.ts, packages/app/src/features/farm-details/dialogs/unstake/logic/getFormFieldsForUnstakeDialog.ts
=> Set form isMaxSelected flag to false after switching asset

packages/common-nodejs/src/logger/Logger.test.ts, packages/common-nodejs/src/logger/utils.ts
Before, promises were logged as `{}`. Now it should be easier to spot such mistakes and fix the logging. 
The best would be to simply prevent from passing `Promise` instances to logger but I don't think it's doable right now...
=> Fix promise logging

packages/app/src/utils/sentry/index.ts
Just a small adjustment to sentry filtering integration. It can be made more strict if we see to much of third party errors at sentry.
=> Be less strict when filtering errors with third party stack frames

eslint.config.js
Added [allowShortCircuit and allowTernary](https://eslint.org/docs/latest/rules/no-unused-expressions#allowshortcircuit-and-allowternary) for [this occurrences](https://github.com/sparkdotfi/spark-app/blob/f79c3c85420f5c029a20ccfdb6add84e58306803/packages/app/src/features/actions/flavours/permit/logic/useCreatePermitHandler.ts#L89) to pass.
=> Add `no-unused-expressions` ESLint rule

packages/common-testnets/src/TestnetClient.test.ts, packages/common-testnets/src/TestnetClient.ts, packages/common-testnets/src/TestnetFactory.test.ts, packages/common-testnets/src/nodes/extendWithTestnetHelpers.ts
Moved client methods test to a separate file. We should increase test coverage there.
=> Add `hasBaselineSnapshot` testnet method

packages/common-universal/src/httpClient/HttpClient.ts
For some reason `instanceof` check didn't work in dns-sentinel even though I was using the same Zod version. I added additional check for `typeName` which solved the problem
=> Improve `ZodString` detection
